server {
    listen 80;
    server_name merchant.xpaylabs.com pay.xpaylabs.com localhost;

    # checkout static files & payment page
    location /checkout {
        proxy_pass http://checkout:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # API to user service (used by checkout and merchant-vue)
    location /api/ {
        proxy_pass http://xpay-user:8077/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # merchant backend API
    location /prod-api/ {
        proxy_pass http://xpay-merchant:8078/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # default → merchant-vue
    location / {
        proxy_pass http://merchant-vue:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
